# Generated by Django 2.1.15 on 2020-09-02 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200901_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('title',
                 models.CharField(
                     max_length=255)),
                ('time_minutes',
                 models.IntegerField()),
                ('price',
                 models.DecimalField(
                     decimal_places=2,
                     max_digits=5)),
                ('link',
                 models.CharField(
                     blank=True,
                     max_length=255)),
                ('ingredients',
                 models.ManyToManyField(
                     to='core.Ingredient')),
                ('tags',
                 models.ManyToManyField(
                     to='core.Tag')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(
                blank=True,
                help_text='The groups this user belongs to. A user will get \
                            all permissions granted to each of their groups.',
                related_name='user_set',
                related_query_name='user',
                to='auth.Group',
                verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(
                default=False,
                help_text='Designates that this user has all permissions \
                            without explicitly assigning them.',
                verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL),
        ),
    ]
